# Generated by Django 5.2.5 on 2025-11-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_contact_address_user_created_at_user_lga_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
            ],
        ),
    ]
