# Generated by Django 5.2.5 on 2025-11-05 02:11

import django.db.models.deletion
import user.helper
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_emailvalidation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business_categories",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="Market_region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_region",
                        to="user.state",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Business_profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(max_length=100)),
                ("business_phone_number", models.CharField(max_length=15)),
                (
                    "aditional_phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("business_address", models.CharField(max_length=200)),
                ("website", models.URLField(blank=True, max_length=20, null=True)),
                ("cac_registration_number", models.CharField(max_length=15)),
                (
                    "cac_file",
                    models.FileField(
                        upload_to=user.helper.generate_unique_filename,
                        verbose_name="cac doc",
                    ),
                ),
                (
                    "trade_license",
                    models.FileField(
                        upload_to=user.helper.generate_unique_filename,
                        verbose_name="Trade license",
                    ),
                ),
                ("tax_identification_number", models.CharField(max_length=20)),
                ("owner_full_name", models.CharField(max_length=60)),
                ("nin_number", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=100)),
                (
                    "business_status",
                    models.CharField(
                        choices=[
                            ("Verified", "Verified"),
                            ("Pending", "Pending"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_categories",
                        to="user.business_categories",
                    ),
                ),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_lga",
                        to="user.lga",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_region",
                        to="user.region",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_state",
                        to="user.state",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="market_region",
                        to="user.market_region",
                    ),
                ),
            ],
        ),
    ]
