# Generated by Django 5.2.5 on 2025-11-05 08:01

import django.db.models.deletion
import user.helper
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_business_categories_alter_user_id_market_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expertise_area",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="business_profile",
            name="owner_full_name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Professional_profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("short_bio", models.CharField(max_length=200)),
                ("years_of_experiance", models.CharField(max_length=10)),
                ("website", models.URLField(blank=True, max_length=20, null=True)),
                (
                    "certificate_file",
                    models.FileField(
                        upload_to=user.helper.generate_unique_filename,
                        verbose_name="Professional certificate",
                    ),
                ),
                ("certification_reg_no", models.CharField(max_length=30)),
                ("tax_identification_number", models.CharField(max_length=20)),
                (
                    "expertise_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expertise_area",
                        to="user.expertise_area",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
