# Generated by Django 5.2.5 on 2025-11-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_expertise_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional_profile",
            name="profile_status",
            field=models.CharField(
                choices=[
                    ("Verified", "Verified"),
                    ("Pending", "Pending"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
