# Generated by Django 5.2.5 on 2025-11-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
