# Generated by Django 5.2.5 on 2025-11-05 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business_profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="professional_profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professional_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
