# Generated by Django 5.2.5 on 2025-11-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_business_profile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional_profile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professional_roles",
                to="user.user_role",
            ),
        ),
    ]
