# Generated by Django 5.2.5 on 2025-11-05 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_professional_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="business_profile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_roles",
                to="user.user_role",
            ),
        ),
    ]
