# Generated by Django 5.2.5 on 2025-11-05 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_business_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business_profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="b2b",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
